export type RelicId =
  | 'aegis-sunken-king'
  | 'vampire-bloodstone'
  | 'tesla-capacitor'
  | 'tome-ancient-ley'
  | 'midas-pouch'
  | 'trickster-die'
  | 'phoenix-feather'
  | 'berserker-pendant'
  | 'brimstone-censer'
  | 'blood-needle'
  | 'chrono-pocketwatch'
  | 'necrotic-urn'
  | 'sunken-aegis'
  | 'gambler-die'
  | 'alchemist-crucible'
  | 'obsidian-shard'
  | 'viper-fang'
  | 'crimson-talisman'
  | 'frostfire-prism'
  | 'thunderstone-coil'
  | 'cursed-skull'
  | 'thornmail-core'
  | 'catalyst-vial'
  | 'soul-harvester'
  | 'warlord-crown'
  | 'voidstone-phylactery'
  | 'celestial-hourglass'
  | 'mirror-retaliation'
  | 'hydra-heart'
  | 'pyromancer-ring'
  | 'glacial-shard'
  | 'stormcaller-beacon'
  | 'shadow-cloak'
  | 'alchemist-pouch'
  | 'dragon-scale'
  | 'cursed-monocle'
  | 'holy-grail'
  | 'boneshard-talisman'
  | 'midas-touch'
  | 'chrono-crystal'
  | 'venomous-barb'
  | 'colossus-shield'
  | 'bloodlust-mask'
  | 'astral-prism';

export type RelicRarity = 'COMMON' | 'UNCOMMON' | 'RARE' | 'EPIC' | 'LEGENDARY';

export interface RelicDefinition {
  id: RelicId;
  name: string;
  rarity: RelicRarity;
  icon: string;
  description: string;
  effect: {
    startOfCombatShield?: number;
    startOfCombatDraw?: number;
    startOfCombatStrength?: number;
    startOfCombatEnergyBonus?: number;
    startOfCombatEvasionTurns?: number;
    onKillPartyHealPercent?: number;
    onKillDrawCards?: number;
    onKillEnergyGain?: number;
    onKillPermanentMaxHp?: number;
    victoryHealPercent?: number;
    manaCostReductionPercent?: number;
    goldMultiplierPercent?: number;
    extraGoldPercent?: number;
    extraShardMultiplierPercent?: number;
    magicCritChanceFlat?: number;
    guardReflectDamage?: number;
    reflectMeleeDamagePercent?: number;
    reviveOnFatalPercent?: number;
    luckFlat?: number;
    burnGainBlock?: number;
    burnNeverDecays?: boolean;
    firstCardFreeHpCost?: number;
    retainCardCount?: number;
    damageVariancePercent?: number;
    poisonApplyBonusDmg?: number;
    poisonGainEnergyOnce?: boolean;
    poisonExtraTrigger?: boolean;
    bleedBonusDmgPercent?: number;
    bleedHitHeal?: number;
    freezeOnBurnSteamDmg?: number;
    freezeBonusBlock?: number;
    shockHitGainBlock?: number;
    lightningFlatBonusDmg?: number;
    startOfCombatEnemyVulnerableTurns?: number;
    startOfCombatEnemyWeakenedTurns?: number;
    thornsReflectDamage?: number;
    dotPotencyMultiplierPercent?: number;
    statusKillHealPercent?: number;
    statusKillDrawCard?: number;
    damageTakenGainNextTurnEnergy?: number;
    everyThreeTurnsDrawExtra?: number;
    potionPotencyMultiplierPercent?: number;
    maxHpBonusFlat?: number;
    extraDraftCardChoice?: number;
    healingReceivedMultiplierPercent?: number;
    skillBlockMultiplierPercent?: number;
    critHealFlat?: number;
  };
}

